"""add

Revision ID: 36c56fdafdd6
Revises: 6cf6426d7cdc
Create Date: 2019-03-25 15:13:39.061650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c56fdafdd6'
down_revision = '6cf6426d7cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('good_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'goods', ['good_id'], ['id'])
    op.drop_column('comment', 'news_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('news_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'goods', ['news_id'], ['id'])
    op.drop_column('comment', 'good_id')
    # ### end Alembic commands ###
